[package]
name = "hbs-table-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.26.0"
geo = "0.18.0"
chrono = "0.4.19"